### ISSUE TITLE
Is this wrapper somehow useful for Cia dsp302 conforme applications?

### ISSUE THREAD

**Issue by brainbubblersbest** [uv-software/PCANBasic-Wrapper#18]
Like the Sontheim MT Application that includes a wrapper for different other hardware from other vendors. Like the peak usb adapter.
I'm in search for a guide to get a Peak_USB adapter running under codesys 2.3
After like 2month I'm about to give up on this.
Can you help me with a hint?
![Uploading Screenshot_20240407_081808_com.android.chrome.jpg…]()

**Comment by uv-software** [comment]
I have no experience with CODESYS and cannot give you any advice. Perhaps you can ask company [CODESYS GmbH](https://www.codesys.com/) directly whether they offer such a solution.

**Comment by uv-software** [comment]
Regarding CiADSP302 profile: The PCANBasic-Wrapper is only a layer 2 API. Higher layer protocols can be based on this.
